name: draggable_widget
description: A flutter package which will help you to create a draggable widget that can be dragged around the screen.
version: 2.0.0
homepage: https://github.com/adar2378
repository: https://github.com/adar2378/draggable_widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
